development:
  adapter: postgresql
  encoding: unicode
  database: railsplate_development

test:
  adapter: postgresql
  encoding: unicode
  database: railsplate_test

production:
  adapter: postgresql
  encoding: unicode
  database: railsplate_production