development:
  adapter: postgresql
  encoding: unicode
  database: rspec_development

test:
  adapter: postgresql
  encoding: unicode
  database: rspec_test

production:
  adapter: postgresql
  encoding: unicode
  database: rspec_production